#!/usr/bin/env python3
"""Regenerate the commit-history table in Memory.md from git.

Everything above the HISTORY marker is hand-written and left alone, so notes
you add by hand survive. Run after landing work:  python3 scripts/update-memory.py
"""
import io
import subprocess

MARKER = '<!-- HISTORY:auto - regenerated by scripts/update-memory.py; edit above this line -->'
REPO = 'https://github.com/chaturvediaksh1304-sudo/Portfolio-Website'

log = subprocess.run(
    ['git', 'log', '--reverse', '--date=short', '--pretty=format:%h|%ad|%s'],
    capture_output=True, text=True, check=True,
).stdout.splitlines()

rows = []
for line in log:
    sha, date, subject = line.split('|', 2)
    rows.append('| %s | [`%s`](%s/commit/%s) | %s |'
                % (date, sha, REPO, sha, subject.replace('|', '\\|')))

table = '\n'.join([
    MARKER,
    '',
    '## Commit history',
    '',
    '%d commits, oldest first.' % len(rows),
    '',
    '| Date | Commit | Change |',
    '| --- | --- | --- |',
    *rows,
    '',
])

doc = io.open('Memory.md', encoding='utf-8').read()
head = doc.split(MARKER)[0] if MARKER in doc else doc.rstrip() + '\n\n'
io.open('Memory.md', 'w', encoding='utf-8').write(head + table)
print('Memory.md: %d commits' % len(rows))
